/** Synth capacities and configuration. */
#include "captool.hpp"
#include <iostream>

using std::endl;

const std::string prologue =
  "#ifndef SYNTI2_CAPACITIES_INCLUDED\n"
  "#define SYNTI2_CAPACITIES_INCLUDED\n";
const std::string epilogue = 
  "#endif\n";
const std::string documentation = 
  "/** @file synti2_cap.h \n"
  " * \n"
  " * OBSERVE: This file is generated by the command line \n"
  " * configurator tool! Editing by hand is not recommended,\n"
  " * and neither should it be necessary. See cltool.cxx for\n"
  " * more details. Some documentation is given below, though.\n"
  " * \n"
  " * This file defines the 'capaities', or limits, of s specific \n"
  " * build of the Synti2 software synthesizer. The idea is that\n"
  " * more restricted custom values can be used in compiling the \n"
  " * final 4k target than those that are used while composing the \n"
  " * music and designing patches. The final 4k executable should\n"
  " * have only the minimum features necessary for its musical score.\n"
  " *\n */\n\n"
  " /* Variables defined here (FIXME: refactor names!!) are:\n"
  "  * NPARTS - multitimbrality; number of max simultaneous sounds;\n"
  "  *          also the number of patches in the patch bank\n"
  "  * NENVPERVOICE - envelopes per voice\n"
  "  * NOSCILLATORS - oscillators/operators per voice\n"
  "  * NCONTROLLERS - oscillators/operators per voice\n"
  "  * NENVKNEES    - number of 'knees' in the envelope\n"
  "  * NDELAYS      - number of delay lines\n"
  "  * DELAYSAMPLES - maximum length of each delay line in samples\n"
  "  * SYNTI2_MAX_SONGBYTES  - maximum size of song sequence data\n"
  "  * SYNTI2_MAX_SONGEVENTS - maximum number of sequence events\n"
  "  */\n\n";

const std::string defaults =
  "#define NPARTS 16\n"
  "#define NENVPERVOICE 6\n"
  "#define NOSCILLATORS 4\n"
  "#define NCONTROLLERS 4\n"
  "\n"
  "#define TRIGGERSTAGE 6\n"
  "#define RELEASESTAGE 2\n"
  "#define LOOPSTAGE 1\n"
  "\n"
  "#define NENVKNEES 5\n"
  "#define SYNTI2_NENVD (NENVKNEES*2)\n"
  "#define NDELAYS 8\n"
  "#define DELAYSAMPLES 0x10000\n"
  "#define SYNTI2_MAX_SONGBYTES 30000\n"
  "#define SYNTI2_MAX_SONGEVENTS 15000\n"
  "\n";

synti2::Capacities::Capacities(std::istream &ist){
  /* FIXME: Implement. */
  return;
}

void
synti2::Capacities::writeCapH(std::ostream &ost){
  ost << prologue;
  ost << documentation;
  ost << defaults;
  ost << "/* FIXME: not yet implemented.*/" << endl;
  ost << epilogue;
}
