all:
	pdflatex instanssi2012_slides_nieminen.tex
	pdflatex instanssi2012_slides_nieminen.tex

mostlyclean:
	-rm *.{aux,log,nav,out,snm,toc} *~

clean: mostlyclean
	-rm instanssi2012_slides_nieminen.pdf
